name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f
        with:
          version: 0.16.0

      - name: Check format
        run: zig fmt --check .

      - name: Build and test
        run: zig build test
